### ISSUE TITLE
ASVZ Login for PHZH Students

### ISSUE THREAD

**Issue by josunym** [fbuetler/asvz-bot#12]
Hi :) i did run the bot (everything works fine) and and then realised i cant acces as a PHZH student... If it wouldnt be to much afford it would be awesome if you can add a login for PHZH   https://auth.asvz.ch/Account/Login

**Comment by fbuetler** [comment]
In general, you should be able to setup an ASVZ account that links to your existing account (check out your asvz id in your profile). You can then choose "ASVZ" as organization to register for trainings.
This way you can use the bot right away and I will look into this issue in the next couple of days.

**Comment by fbuetler** [comment]
PHZH is now supported.
