### ISSUE TITLE
Element on website not found

### ISSUE THREAD

**Issue by cvonholly** [fbuetler/asvz-bot#16]
When running asvz_bot.py with a valid lesson ID, the script was not able to find the element

2023-02-02 09:19:49 ERROR    Element on website not found! This may happen when the website was updated recently. Please report this incident to: https://github.com/fbuetler/asvz-bot/issues

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dl[contains(., 'Datum/Zeit')]/dd"}
  (Session info: headless chrome=...)

**Comment by fbuetler** [comment]
I cannot reproduce this issue. This works just fine for me:

```python
python asvz_bot.py lesson 377593
```

What version are you using?

**Comment by cvonholly** [comment]
I deleted the json file and logged in again and it worked. Sorry for the inconviniece
