### ISSUE TITLE
Not working with chromium and linux on raspberry pi as there is no compatible driver

### ISSUE THREAD

**Issue by kevchef** [fbuetler/asvz-bot#17]
Thanks for the great work. 
It is highly appreciated.

After using it on my desktop computer I tried to run the script remotety on a raspberry pi where chrome is not available.
Unfortunately this did not work as selenium did not find a matching driver for chromium. 
Could this be extended to work on raspbian (Firefox)?

**Comment by fbuetler** [comment]
Hi, 

As far as I know, you are right and chrome is not build natively for the raspberry pi. However, you can install chromium with a simple 

```bash
sudo apt-get update & sudo apt-get install chromium-browser --yes
```

The script should work with chrome and chromium.

But if you indeed want to run the script with the gecko driver (firefox), this is also possible with some little tweaks of the script.
See the [webdriver doc](https://github.com/SergeyPirogov/webdriver_manager#use-with-firefox) and the [selenium doc](https://selenium-python.readthedocs.io/getting-started.html) for reference.
