### ISSUE TITLE
ChromeDriver and Chrome version incompatible

### ISSUE THREAD

**Issue by Glanfaloth** [fbuetler/asvz-bot#30]
Hey Florian,

Haven't been using this for a long time and today I got this error when running
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.187 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```
I couldn't find an older version of Chrome... Any fix? Thanks!

**Comment by JonathanLehner** [comment]
DM

**Comment by code-inflation** [comment]
Upgrading `webdriver-manager` may fix this issue.

**Comment by fbuetler** [comment]
Can you please check the latest version (1.4.6) if the issue persists? I updated the `webdriver-manager` and it works with `chromium 117.0.5938.149` on my machine.
