### ISSUE TITLE
Element on website not found

### ISSUE THREAD

**Issue by Danielasantosc** [fbuetler/asvz-bot#31]
Hi Florian,
I started using the bot today and I got this error while running:

```
2023-09-26 19:49:43 INFO     Checking login credentials
2023-09-26 19:49:52 INFO     Login to 'Universität Zürich'
2023-09-26 19:50:00 ERROR    Element on website not found! This may happen when the website was updated recently.
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='password']"}
```

**Comment by fbuetler** [comment]
Looks like UZH has switched from their own login page to use SWITCH. Unfortunately, this requires some more work and I will have a look into it in the next couple of days.

As a quick workaround, see my response to another issue:

> In general, you should be able to setup an ASVZ account that links to your existing account (check out your asvz id in your profile). You can then choose "ASVZ" as organization to register for trainings. This way you can use the bot right away and I will look into this issue in the next couple of days.

https://github.com/fbuetler/asvz-bot/issues/12#issuecomment-1290067221

**Comment by fbuetler** [comment]
Please try the newest version of the script. You should be able to use your UZH login again.
