### ISSUE TITLE
Events not supported

### ISSUE THREAD

**Issue by masus04** [fbuetler/asvz-bot#36]
`Event`s are not supported. Events are different from `lesson` and `training` in that they represent a block of n lessons that have to be booked in advance, e.g. [Bogensport](https://schalter.asvz.ch/tn/events/537541).

In order to support this, the bot would also have to support searching further into the future than one week.

**Comment by fbuetler** [comment]
There is an ongoing PR https://github.com/fbuetler/asvz-bot/pull/34 that is going to support events.
