### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by julesmefy** [fbuetler/asvz-bot#6]
Sorry I am a programming noob. Where do I save it locally (where is .asvz-bot.json). Also does the program run on repl.it?
Thank you!

**Comment by fbuetler** [comment]
Hi,
The `asvz-bot.json` file is automatically stored in the `src` folder, if you use the appropriate flag. As it is a "dot"-file it is by default hidden in UNIX systems. To view it try `ls -al` in your terminal in the `src` folder. 
I haven't tested the bot with `repl.it` and neither do I know whether selenium has a driver for it. If you find one that works, let me know!
Cheers

**Comment by julesmefy** [comment]
Hi, Thank you for your kind comment. I tried everything now and am still unable to get the bot to work. Could you run me through step by step what I have to do after opening the IDLE Shell 3.10.0. Sorry for causing you such a hassle! Thank you for your help!

**Comment by fbuetler** [comment]
This should do it:
```
git clone git@github.com:fbuetler/asvz-bot.git
cd asvz-bot/src
python3 -m pip install -r requirements.txt
python3 asvz_bot.py -u <nethz> -p <passwod> -org <organisation> lesson <lesson id>
```
