### ISSUE TITLE
ASVZ login direkt als alumni

### ISSUE THREAD

**Issue by Hermain** [fbuetler/asvz-bot#7]
Hallo
Ich versucht das hier für einen Freund einzurichten. Er ist alumni und hat einen direkten ASVZ login. Die Org ASVZ gibt es aber nicht und ZHAW (wo er früher hingehörte) klappt nicht.
Ist es viel Aufwand das für den ASVZ Login hinzubiegen? (https://auth.asvz.ch/Account/Login)

**Comment by fbuetler** [comment]
Hi,
No, it should not be a lot of work and @abrandemuehl actually implemented that in a fork so maybe he wants to submit a pull request? :)

**Comment by abrandemuehl** [comment]
Sure, I can make a PR. Unfortunately I've only tried it a couple times so there may be some bugs that shake out

**Comment by fbuetler** [comment]
Closing, as this feature is now integrated. Thanks a lot!
