### ISSUE TITLE
No version satisfies venv

### ISSUE THREAD

**Issue by LinoHofstetter** [fbuetler/asvz-bot#9]
When I execute 

cd src
python3 -m pip install venv
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install -r requirements.txt
python3 asvz_bot.py -h

in the terminal, it throws these two errors. Any idea why?

ERROR: Could not find a version that satisfies the requirement venv (from versions: none)
ERROR: No matching distribution found for venv

**Comment by fbuetler** [comment]
What happens if you omit `python3 -m pip install venv`?
That means:
```
cd src
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install -r requirements.txt
python3 asvz_bot.py -h
```
